from pathlib import Path
import re


PROJECT_DIR = Path(__file__).resolve().parents[1]


def generated_python_version(lockfile: str) -> str:
    content = (PROJECT_DIR / lockfile).read_text(encoding="utf-8")
    match = re.search(r"autogenerated by pip-compile with Python (\d+\.\d+)", content)
    assert match, f"{lockfile} 缺少 pip-compile Python 版本头"
    return match.group(1)


def test_dependency_lock_verification_uses_windows_python_matching_locks() -> None:
    workflow = (PROJECT_DIR / ".github" / "workflows" / "ci.yml").read_text(encoding="utf-8")
    job = re.search(
        r"^  verify-dependency-locks:\n(?P<body>.*?)(?=^  [a-z][a-z0-9_-]*:|\Z)",
        workflow,
        flags=re.MULTILINE | re.DOTALL,
    )
    assert job, "CI 缺少独立的依赖锁校验任务"
    body = job.group("body")
    assert re.search(r"^    runs-on: windows-latest$", body, flags=re.MULTILINE)
    match = re.search(r'python-version:\s*"(\d+\.\d+)"', body)
    assert match, "依赖锁校验任务未声明 Python 版本"

    expected = generated_python_version("requirements.lock")
    assert generated_python_version("requirements-dev.lock") == expected
    assert match.group(1) == expected
