"""Data retention service — clean up expired snapshots and collection runs."""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timedelta
from zoneinfo import ZoneInfo

from sqlalchemy import delete, func, select, text, update
from sqlalchemy.orm import Session

from models.dashboard_collection_run import CollectionRun
from models.dashboard_metric import MetricAcc, MetricCurrent, MetricSnapshot

logger = logging.getLogger(__name__)

# Default retention periods (days).
_DEFAULT_SNAPSHOT_DAYS = 7
_DEFAULT_RUN_DAYS = 7
_DEFAULT_ACC_DAYS = 90
_DEFAULT_ACTIVE_RUN_TIMEOUT_MINUTES = 120
_PARTITION_AHEAD_DAYS = 30
_DAILY_PARTITION_PATTERN = re.compile(r"^p(\d{8})$")
_MAX_RETENTION_DAYS = 3650
_MAX_ACTIVE_RUN_TIMEOUT_MINUTES = 7 * 24 * 60


def _bounded_int(value: object, name: str, *, minimum: int, maximum: int) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{name} 必须是整数") from exc
    if not minimum <= parsed <= maximum:
        raise ValueError(f"{name} 必须在 {minimum}-{maximum} 之间")
    return parsed


def _shanghai_now() -> datetime:
    return datetime.now(ZoneInfo("Asia/Shanghai")).replace(tzinfo=None)


def recover_stale_collection_runs(
    session: Session,
    *,
    active_run_timeout_minutes: int = _DEFAULT_ACTIVE_RUN_TIMEOUT_MINUTES,
    now: datetime | None = None,
) -> int:
    """Close abandoned active runs and commit the recovery independently."""
    timeout_minutes = _bounded_int(
        active_run_timeout_minutes,
        "active_run_timeout_minutes",
        minimum=1,
        maximum=_MAX_ACTIVE_RUN_TIMEOUT_MINUTES,
    )
    resolved_now = now or _shanghai_now()
    active_run_cutoff = resolved_now - timedelta(minutes=timeout_minutes)
    result = session.execute(
        update(CollectionRun)
        .where(
            CollectionRun.status.in_(["PENDING", "RUNNING"]),
            func.coalesce(
                CollectionRun.updated_at,
                CollectionRun.started_at,
                CollectionRun.created_at,
            ) < active_run_cutoff,
        )
        .values(
            status="FAILED",
            phase="RECOVER_TIMEOUT",
            finished_at=resolved_now,
            error_type="STALE_RUN_TIMEOUT",
            error_message=json.dumps(
                {
                    "message": "采集进程未正常收口，已自动标记为超时失败",
                    "timeout_minutes": timeout_minutes,
                },
                ensure_ascii=False,
            ),
            updated_at=resolved_now,
        )
    )
    session.commit()
    return result.rowcount


def _partition_day(name: str) -> datetime | None:
    match = _DAILY_PARTITION_PATTERN.fullmatch(name)
    if not match:
        return None
    try:
        return datetime.strptime(match.group(1), "%Y%m%d")
    except ValueError:
        return None


def _daily_partition_clause(day: datetime) -> str:
    boundary = day + timedelta(days=1)
    return (
        f"PARTITION p{day:%Y%m%d} "
        f"VALUES LESS THAN ('{boundary:%Y-%m-%d}')"
    )


def _maintain_mysql_snapshot_partitions(
    session: Session,
    *,
    now: datetime,
    retention_days: int,
) -> dict[str, int]:
    bind = session.get_bind()
    if bind.dialect.name != "mysql":
        return {"partition_drop_count": 0, "partition_create_count": 0}

    partition_names = list(session.scalars(text("""
        SELECT PARTITION_NAME
        FROM information_schema.PARTITIONS
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_NAME = 'metric_snapshot'
          AND PARTITION_NAME IS NOT NULL
    """)).all())
    if "p_future" not in partition_names:
        return {"partition_drop_count": 0, "partition_create_count": 0}

    dated_partitions = sorted(
        (day, name)
        for name in partition_names
        if (day := _partition_day(name)) is not None
    )
    cutoff_day = (now - timedelta(days=retention_days)).date()
    drop_names = [
        name for day, name in dated_partitions if day.date() < cutoff_day
    ]
    if "p_history" in partition_names and cutoff_day > datetime(2026, 1, 1).date():
        drop_names.insert(0, "p_history")
    if drop_names:
        # Names are generated by this service or validated by a strict regex.
        session.execute(text(
            "ALTER TABLE metric_snapshot DROP PARTITION " + ", ".join(drop_names)
        ))

    remaining_days = [
        day for day, name in dated_partitions if name not in drop_names
    ]
    horizon = (now + timedelta(days=_PARTITION_AHEAD_DAYS)).date()
    first_new_day = (
        max(remaining_days) + timedelta(days=1)
        if remaining_days
        else datetime.combine(cutoff_day, datetime.min.time())
    )
    new_days: list[datetime] = []
    cursor = first_new_day
    while cursor.date() <= horizon:
        new_days.append(cursor)
        cursor += timedelta(days=1)
    if new_days:
        clauses = [_daily_partition_clause(day) for day in new_days]
        clauses.append("PARTITION p_future VALUES LESS THAN (MAXVALUE)")
        session.execute(text(
            "ALTER TABLE metric_snapshot REORGANIZE PARTITION p_future INTO ("
            + ", ".join(clauses)
            + ")"
        ))

    return {
        "partition_drop_count": len(drop_names),
        "partition_create_count": len(new_days),
    }


def cleanup_expired_data(
    session: Session,
    *,
    snapshot_retention_days: int = _DEFAULT_SNAPSHOT_DAYS,
    run_retention_days: int = _DEFAULT_RUN_DAYS,
    acc_retention_days: int = _DEFAULT_ACC_DAYS,
    active_run_timeout_minutes: int = _DEFAULT_ACTIVE_RUN_TIMEOUT_MINUTES,
) -> dict[str, int]:
    """Delete expired snapshots, collection runs and old accumulated metrics.

    Deletion order respects FK dependencies:
    1. Delete expired ``metric_snapshot`` and ``metric_acc`` rows.
    2. Delete finished ``collection_run`` rows only when no metric table still
       references them. ``metric_current`` is retained and therefore keeps its
       latest collection run alive.

    Stale ``PENDING`` / ``RUNNING`` runs are first closed as ``FAILED``.

    Returns counts of deleted rows per table.
    """
    snapshot_retention_days = _bounded_int(
        snapshot_retention_days,
        "snapshot_retention_days",
        minimum=1,
        maximum=_MAX_RETENTION_DAYS,
    )
    run_retention_days = _bounded_int(
        run_retention_days,
        "run_retention_days",
        minimum=1,
        maximum=_MAX_RETENTION_DAYS,
    )
    acc_retention_days = _bounded_int(
        acc_retention_days,
        "acc_retention_days",
        minimum=1,
        maximum=_MAX_RETENTION_DAYS,
    )
    active_run_timeout_minutes = _bounded_int(
        active_run_timeout_minutes,
        "active_run_timeout_minutes",
        minimum=1,
        maximum=_MAX_ACTIVE_RUN_TIMEOUT_MINUTES,
    )
    now = _shanghai_now()
    # Sparse history depends on the first full checkpoint of each day.  Keep
    # the entire boundary day; deleting at the current clock time could remove
    # its midnight checkpoint and leave only a partial set of later changes.
    snapshot_cutoff = (now - timedelta(days=snapshot_retention_days)).replace(
        hour=0,
        minute=0,
        second=0,
        microsecond=0,
    )
    run_cutoff = now - timedelta(days=run_retention_days)
    acc_cutoff_date = (now - timedelta(days=acc_retention_days)).date()
    stale_run_recovered = recover_stale_collection_runs(
        session,
        active_run_timeout_minutes=active_run_timeout_minutes,
        now=now,
    )

    partition_result = _maintain_mysql_snapshot_partitions(
        session,
        now=now,
        retention_days=snapshot_retention_days,
    )

    # Step 1 — delete expired snapshots
    snapshot_result = session.execute(
        delete(MetricSnapshot).where(
            MetricSnapshot.collected_at < snapshot_cutoff,
        )
    )
    snapshot_deleted = snapshot_result.rowcount

    # Step 2 — delete expired accumulated metrics (older than retention)
    acc_result = session.execute(
        delete(MetricAcc).where(
            MetricAcc.stat_date < acc_cutoff_date,
        )
    )
    acc_deleted = acc_result.rowcount

    # Step 3 — delete only runs that have no remaining FK references.
    # Correlated NOT EXISTS checks avoid loading a potentially large ID list and
    # keep the eligibility check and deletion in one database statement.
    run_result = session.execute(
        delete(CollectionRun).where(
            CollectionRun.created_at < run_cutoff,
            CollectionRun.status.in_(["SUCCESS", "FAILED"]),
            ~select(MetricCurrent.id).where(
                MetricCurrent.collection_run_id == CollectionRun.id,
            ).exists(),
            ~select(MetricSnapshot.id).where(
                MetricSnapshot.collection_run_id == CollectionRun.id,
            ).exists(),
            ~select(MetricAcc.id).where(
                MetricAcc.collection_run_id == CollectionRun.id,
            ).exists(),
        )
    )
    run_deleted = run_result.rowcount

    session.commit()

    if (
        snapshot_deleted
        or stale_run_recovered
        or run_deleted
        or acc_deleted
        or partition_result["partition_drop_count"]
        or partition_result["partition_create_count"]
    ):
        logger.info(
            "数据清理完成: 快照删除 %d 行, 累计删除 %d 行, "
            "超时批次恢复 %d 个, 采集记录删除 %d 行, 分区删除 %d 个, 分区新建 %d 个",
            snapshot_deleted,
            acc_deleted,
            stale_run_recovered,
            run_deleted,
            partition_result["partition_drop_count"],
            partition_result["partition_create_count"],
        )

    return {
        "snapshot_deleted": snapshot_deleted,
        "acc_deleted": acc_deleted,
        "stale_run_recovered": stale_run_recovered,
        "run_deleted": run_deleted,
        **partition_result,
    }
